# totask2 spring configuration
#
# @author man-at-home
#

app:
   name: totask2
   description: ${app.name} work entry logging (default env)
   version: v0.0-dev

spring:
   thymeleaf:
      cache: false

   datasource:
       initialize: true
           
   jpa:
      show-sql: true   
      hibernate:
         ddl-auto: create-drop

flyway:
   enabled: false
