# totask2 "QA" spring configuration
#
# @author Manfred
#

app:
   name: totask2
   description: ${app.name} work entry logging (qa)
   version: v0.0-qa

spring:
   thymeleaf:
      cache: true

   datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:totask2.qa.db
    
   jpa:
      database: H2
      show-sql: true
      hibernate:
         ddl-auto: none
         dialect: org.hibernate.dialect.H2Dialect
 
# db migration settings enabled
flyway:
   enabled: true
